changes to show problems of integrating cython with swig
error is

E
======================================================================
ERROR: testEnsemblePot (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File
"/home/garyt/Dropbox/git/xcamshift/xcamshift/src/cython/testEnsemblePot.py",
line 26, in setUp
    potList.append(pot)
  File
"/home/garyt/programs/xplor-nih/2.31.0/python/wrappers/potList.py", line
186, in append
    return self.renamed_add(pot)
  File
"/home/garyt/programs/xplor-nih/2.31.0/python/wrappers/potList.py", line
208, in renamed_add
    def renamed_add(self, *args, **kwargs): return
_potList.PotList_renamed_add(self, *args, **kwargs)
TypeError: swig/py exception: fromPy(Pot): error converting
potProxy.PotProxy to ptr

----------------------------------------------------------------------
Ran 1 test in 0.034s

FAILED (errors=1)