remove a cython compilation error due to declaration after use
_bytes_to_target_components is declared in  Fast_non_bonded_calculator
and used in New_fast_non_bonded_calculator. However,
New_fast_non_bonded_calculator was declared before
Fast_non_bonded_calculator leading to a compilation error:

((<FileSourceDescriptor:/import/bc2/home/guest/grzesiek/leung/software/xcamshift/xcamshift/src/cython2/Cython_shift_calculator.pyx>,
1831, 86), u"Cannot convert 'Non_bonded_target_component **' to Python 
object")
((<FileSourceDescriptor:/import/bc2/home/guest/grzesiek/leung/software/xcamshift/xcamshift/src/cython2/Cython_shift_calculator.pyx>,
1834, 86), u"Cannot convert 'Non_bonded_remote_atom_component **' to 
Python object")
((<FileSourceDescriptor:/import/bc2/home/guest/grzesiek/leung/software/xcamshift/xcamshift/src/cython2/Cython_shift_calculator.pyx>,
1856, 40), u"Cannot convert Python object to 'Vec3'")
((<FileSourceDescriptor:/import/bc2/home/guest/grzesiek/leung/software/xcamshift/xcamshift/src/cython2/Cython_shift_calculator.pyx>,
1870, 40), u"Cannot convert Python object to 'Vec3'")

bug spotted and fix suggested by Hoi Tik Alvin Leung (@htal2)